### ISSUE TITLE
README.md stap 3

### ISSUE THREAD

**Issue by vangeest** [emmauscollege/4HV-website-template#1]
stap 3 uit de README.md is lastig voor leerlingen. Ze moeten eerst een layout maken en dan pas de inhoud erin zetten. Hun intuitie geeft ze de ingeving om eerst de plaatjes en tekst erin te zetten en dan pas de layout te maken. Misschien kunnen we de aanpak hieraan aanpassen.

**Comment by cam-emmauscollege** [comment]
Dit is een lastige, maar wel een zeer terechte. Ik twijfel of een simpele omkering weer niet andere problemen oplevert

**Comment by vangeest** [comment]
Wat stel je voor: omkeren (en tekst even nalopen) of maar zo laten?

**Comment by vangeest** [comment]
Het stappenplan is inmiddels verplaatst naar de informatica website. Ik heb stap 3 (maken layout) verduidelijkt op de informatica website en de volgorde niet aangepast.
