### ISSUE TITLE
ZweefLinks aanpassen

### ISSUE THREAD

**Issue by vangeest** [emmauscollege/4HV-website-template#2]
Leerlingen die float willen gebruiken om plaatjes en tekst in kolommen te zetten binnen een article worden door de zweefLinks class in het voorbeeld op het verkeerde pad gezet. Voorstel tot aanpassing: 2 articles maken, de eerste met een plaatje gecentreerd (margin: auto), de tweede met tekst over de volle breedte

**Comment by cam-emmauscollege** [comment]
Wil je twee articles in dezelfde pagina, of wil je de verschillen op twee verschillende pagina's. En ik begrijp nog niet helemaal wat het probleem *precies* veroorzaakt.

**Comment by vangeest** [comment]
fixed in pull #8
