### ISSUE TITLE
extra header tags

### ISSUE THREAD

**Issue by cam-emmauscollege** [emmauscollege/4HV-website-template#3]
voor een naadloze ervaring wil ik graag in de header meta tags opnemen voor de utf-8 en cache gedrag. De laatste werkt niet altijd gegarandeerd, maar wie weet...

**Comment by vangeest** [comment]
Prima. Ik zal morgen
Ik heb overigens eerder dit jaar in de .gitpod.yml als een aanpassing gedaan zodat de webserver die gitpod gebruikt info in de http header meestuurt die er (meestal?) voor zorgt dat er niet gecached wordt
